version: '2'

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: gndi123
      MYSQL_USER: gndiuser
      MYSQL_PASSWORD: gndi123
      MYSQL_DATABASE: gndi
    hostname: mysql
    networks:
      - gndi

  gndi-spring-backend:
    container_name: gndi-spring-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: gndi-spring-backend:latest
    ports:
      - "8080:8080"
    hostname: spring
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - gndi
    environment:
      - spring.datasource.url=jdbc:mysql://mysql/gndi?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=gndi123
      - spring.jpa.properties.hibernate.hbm2ddl.auto=create
      - spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      - gndi.app.jwtSecret=piPjBnPipdw-k3URVITwlbtWXmMZSkq21JNG-cBCM_DFitgzOYgnHiR9Rp2r5z_ghoFOrXcSaNJDMgfttGkUDX0nntivnPHQYO_oSg0QSWJIZxfiXOb-IzYA9PPnOkC16fMeFZA1TOQDyDcp752qQ-cyEZ409O0jecAxgZHtjUyjFu6ZHDk_wHEEXbsDNFueGb6PQZ3_UGA5ePggdGM4_GSWo7owvuqmuhKfdMXX0vUQeIPjYH000cVuIUWPH4rYl9lLeCMdea3UBAUE6si8uKJ6lgV59r0OkkLoU5ZXdXPgCaJRRibwBGggqpTS38S8yq6yRMObbQNvb_CCq39_Gw
      - gndi.app.jwtExpirationMs=60000
      - gndi.app.jwtRefreshExpirationMs=120000

networks:
  gndi:
